spring:
#    banner-mode: off
  application:
    name: artemis-producer
  profiles:
    active: local
#  devtools:
#    livereload:
#      enabled: false

# Logging configuration print only current thread and messages for demo purposes
logging:
  pattern:
    console: "[%thread]:%msg%n"
  level:
    com.memorynotfound: "debug"
    org.springframework: info
debug: false
---
spring:
  config:
    activate:
      on-profile: local
  artemis:
       broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
       pool:
         block-if-full: true
         block-if-full-timeout: -1
         enabled: false
         idle-timeout: 30000
         max-connections: 1
         time-between-expiration-check: -1
         use-anonymous-producers: true
  jms:
    pub-sub-domain: true
#  artemis:
#    mode: native
#    host: localhost
#    port: 61616
#    user: user
jms.topic.destination : demoTopic
jms.queue.destination : demoQueue

---
spring:
  config:
    activate:
      on-profile: clustered-topic
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: user
    password: password
  jms:
    pub-sub-domain: true
jms.queue.destination : demoQueue
jms.topic.destination : demoTopic
